training:
  epochs: 20
  lr: 0.005
  batch_size: 32

model:
  version: 1
  size: 101
  classes:
  - "human"
  - "bicycle"
  - "motorcycle"
  - "vehicle"
  expose_featuremap: False

data:
  root: "/Data/Harborfront_raw/"
  train: "../Train_data.csv"
  valid: "../Valid_data.csv"
  test: "../Test_data.csv"
  