training:
  epochs: 20
  lr: 0.1
  lr_steps: 5000
  lr_decay: 0.9
  batch_size: 32
  validation_steps: 10000

model:
  size: 56
  classes:
  - "human"
  - "bicycle"
  - "motorcycle"
  - "vehicle"
  expose_featuremap: False
  name: "ResNet56_4_class"
  exp: "baseline01"

data:
  root: "/Data/Harborfront_raw/"
  train: "data/Train_data.csv"
  valid: "data/Valid_data.csv"
  test: "data/Test_data.csv"
  im_size: 
  - 288
  - 384
  - 3
  binary_cls: True

wandb:
  log_freq: 100 #Number of batches