training:
  epochs: 20
  lr: 0.1
  lr_steps: 5000
  lr_decay: 0.9
  batch_size: 16
  validation_steps: 10000

model:
  size: 56
  classes:
  - "human"
  expose_featuremap: False
  name: "ResNet56_human_hires"
  exp: "higher resolution test for SIDU"

data:
  root: "/Data/Harborfront_raw/"
  train: "data/Train_data.csv"
  valid: "data/Valid_data.csv"
  test: "data/Test_data.csv"
  im_size: 
  - 576
  - 768
  - 3
  binary_cls: True

wandb:
  log_freq: 200 #Number of batches