training:
        epochs: 5
        lr: 0.05
        lr_steps: 5000
        lr_decay: 0.88
        batch_size: 32
        validation_steps: 10000

unlearning:
        noise_scale: 1
        noise_scale_2: 0.01
        epochs_2: 10
        transpose: True
        reinit_last: True  
        train_dense: True

model:
        size: 56
        classes:
                - "human"
                - "bicycle"
                - "motorcycle"
                - "vehicle"
        expose_featuremap: False
        name: "ResNet56_forget_human"
        exp: "vc_b32_2rounds_e5_1_e5_0.01_trans_dense_target_ignore"

data:
        root: "/Data/Harborfront_raw/"
        train: "/Data/REPAI_WS/Train_data.csv"
        valid: "/Data/REPAI_WS/Valid_data.csv"
        test: "/Data/REPAI_WS/Test_data.csv"
        img_size:
        - 288
        - 384
        - 3
        binary_cls: True

wandb:
        log_freq: 100
